### ISSUE TITLE
Menu Display (CSS) is all messed up and I cannot use it.

### ISSUE THREAD

**Issue by Foxgluvs** [TheWebTech/HubSpot-Developer-Extension#238]
Menu Display (CSS) is all messed up and I cannot use it. rebooted, cleared cache, removed and re-added extension.
If I INSPECT with DevTools an element in the menu, then it widens up and I can see the menu again.

Windows 10, Chrome Browser.

![HubSpotDevMenu_MessedUp](https://user-images.githubusercontent.com/72869790/120029719-79a0ab00-bfc4-11eb-8451-d00dd1b1827f.PNG)

**Comment by ericsalvi** [comment]
This happens when upgrading from Chrome 90 to Chrome 91.

**Comment by Foxgluvs** [comment]
This is also showing the same way when I use the Chrome extension within IE Edge. Is there a plan to fix this or should I be looking for something else?

**Comment by GonzaloTorreras** [comment]
[Fix](https://github.com/TheWebTech/HubSpot-Developer-Extension/tree/bug-chrome-v91-popup) will be live soon.
I found it's related to vw units, so I replaced our logic in the CSS instead of trying to make it work with them.
